//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CLUBDBEntities : DbContext
    {
        public CLUBDBEntities()
            : base("name=CLUBDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Center> Centers { get; set; }
        public virtual DbSet<Club> Clubs { get; set; }
        public virtual DbSet<MemberShip> MemberShips { get; set; }
        public virtual DbSet<President> Presidents { get; set; }
        public virtual DbSet<PresidentClub> PresidentClubs { get; set; }
        public virtual DbSet<Student> Students { get; set; }
    }
}
